"""add ai_brief_feedback created_at index + sync drift

Revision ID: 72093d36dca9
Revises: 38c36c7b12df
Create Date: 2026-04-21 04:26:26.633941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72093d36dca9'
down_revision: Union[str, Sequence[str], None] = '38c36c7b12df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ai_fb_created_at', 'ai_brief_feedback', ['created_at'], unique=False)
    op.drop_index(op.f('ix_limit_up_industry'), table_name='limit_up_records')
    op.create_index(op.f('ix_limit_up_records_industry'), 'limit_up_records', ['industry'], unique=False)
    op.alter_column('market_sentiment', 'one_word_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('market_sentiment', 'one_word_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_limit_up_records_industry'), table_name='limit_up_records')
    op.create_index(op.f('ix_limit_up_industry'), 'limit_up_records', ['industry'], unique=False)
    op.drop_index('ix_ai_fb_created_at', table_name='ai_brief_feedback')
    # ### end Alembic commands ###
